server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-integration-example?useSSL=false
    username: root
    password: root
#  servlet:
#    multipart:
#      max-file-size: 500MB      # 单个文件大小（Mb和Kb都可以）
#      max-request-size: 2048MB  # 连续上传文件大小

#mybatis:
#  mapper-locations: classpath:com/mapper/xml/*.xml
#  type-aliases-package: com.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/baba/mybatisplus/**/*Mapper.xml

openHttps: close #关闭https

swagger:
  enable: true #启动swagger
